function HelloWorld() {var a={load:function(){},bind:function(b,a,d){var f=Array.prototype.slice.call(arguments,2);return function(){var d,g=[];for(d=0;d<f.length;d++)g.push(f[d]);for(d=0;d<arguments.length;d++)g.push(arguments[d]);return a.apply(b,g)}},clone:function(b,c,d,f){var e;switch(a.getClassName(b)){case "number":case "string":case "boolean":case "function":case "null":case "undefined":c=b;break;case "Array":if(null===c||void 0===c)c=[];for(e in b)c[e]=f?a.clone(b[e],c[e],d,f):b[e];break;default:if(null===
c||void 0===c)c={};for(e in b)c[e]=d?a.clone(b[e],c[e],d,f):b[e]}return c},setObj:function(b,c){for(var d in c){var f=b[d];if(void 0!==f){var e=c[d];"LZR.Base.ValCtrl"===a.getClassName(f)&&"LZR.Base.ValCtrl"!==a.getClassName(e)?f.set(e,!1):b[d]=e}}},getClassName:function(b){if(null===b)return"null";var a=typeof b;if("object"!=a)return a;a=Object.prototype.toString.apply(b);a=a.substring(8,a.length-1);if("Object"==a){if(b.className_)return b.className_;var d=b.constructor;if(d==Object)return a;if(b.prototype&&
"classname"in b.prototype.constructor&&"string"==typeof b.prototype.constructor.classname)return d.prototype.classname}return a},initSuper:function(b){for(var a=0;a<b.super_.length;a++)b.super_[a].call(b,{super_:b.super_[a]})}};a.load(["LZR"],"LZR.HTML5");a.HTML5=function(b){b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.HTML5.prototype.className_="LZR.HTML5";a.HTML5.prototype.version_="1.0";a.load(null,"LZR.HTML5");a.HTML5.prototype.init_=function(b){b&&a.setObj(this,b)};a.load(["LZR.HTML5"],
"LZR.HTML5.Project");a.HTML5.Project=function(b){b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.HTML5.Project.prototype.className_="LZR.HTML5.Project";a.HTML5.Project.prototype.version_="1.0";a.load(null,"LZR.HTML5.Project");a.HTML5.Project.prototype.init_=function(b){b&&a.setObj(this,b)};a.load(["LZR.HTML5.Project"],"LZR.HTML5.Project.Bp");a.HTML5.Project.Bp=function(b){b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.HTML5.Project.Bp.prototype.className_="LZR.HTML5.Project.Bp";
a.HTML5.Project.Bp.prototype.version_="1.0";a.load(null,"LZR.HTML5.Project.Bp");a.HTML5.Project.Bp.prototype.init_=function(b){b&&a.setObj(this,b)};a.load(["LZR.HTML5.Project.Bp"],"LZR.HTML5.Project.Bp.StationInfo");a.HTML5.Project.Bp.StationInfo=function(b){b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.HTML5.Project.Bp.StationInfo.prototype.className_="LZR.HTML5.Project.Bp.StationInfo";a.HTML5.Project.Bp.StationInfo.prototype.version_="1.0";a.load(null,"LZR.HTML5.Project.Bp.StationInfo");
a.HTML5.Project.Bp.StationInfo.prototype.init_=function(b){b&&a.setObj(this,b)};a.load(["LZR"],"LZR.Base");a.Base=function(b){b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.Base.prototype.className_="LZR.Base";a.Base.prototype.version_="1.0";a.load(null,"LZR.Base");a.Base.prototype.init_=function(b){b&&a.setObj(this,b)};a.load(["LZR.Base","LZR.Base.ValCtrl.Event"],"LZR.Base.ValCtrl");a.Base.ValCtrl=function(b){this.val=null;this.autoEvent=this.enableEvent=!0;this.event=new a.Base.ValCtrl.Event({self:this});
b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.Base.ValCtrl.prototype.className_="LZR.Base.ValCtrl";a.Base.ValCtrl.prototype.version_="1.0";a.load(null,"LZR.Base.ValCtrl");a.Base.ValCtrl.prototype.get=function(){return val};a.Base.ValCtrl.prototype.set=function(b,a){if(!1===a)this.val=b;else if(this.enableEvent){var d=this.val;!1!==this.beforeSet(b,this,d)&&(b!==this.val&&(this.val=b,this.onChange(b,this,d)),this.onSet(b,this,d))}else this.enableEvent=this.autoEvent,this.val=b};
a.Base.ValCtrl.prototype.setEventObj=function(b){this.event.before.obj=b;this.event.change.obj=b;this.event.set.obj=b};a.Base.ValCtrl.prototype.beforeSet=function(b,a,d){return this.event.before.execute(b,a,d)};a.Base.ValCtrl.prototype.onChange=function(b,a,d){return this.event.change.execute(b,a,d)};a.Base.ValCtrl.prototype.onSet=function(b,a,d){return this.event.set.execute(b,a,d)};a.Base.ValCtrl.prototype.init_=function(b){b&&(this.val=b)};a.load(["LZR.Base","LZR.Base.CallBacks.CallBack"],"LZR.Base.CallBacks");
a.Base.CallBacks=function(b){this.autoEvent=this.enableEvent=!0;this.obj=this;this.count=0;this.m_CallBack={};b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.Base.CallBacks.prototype.className_="LZR.Base.CallBacks";a.Base.CallBacks.prototype.version_="1.0";a.load(null,"LZR.Base.CallBacks");a.Base.CallBacks.prototype.append=function(b,c){if(void 0===c||null===c)c=this.count;void 0===this.m_CallBack[c]&&this.count++;this.m_CallBack[c]=new a.Base.CallBacks.CallBack({name:c,fun:b})};
a.Base.CallBacks.prototype["delete"]=function(b){void 0!==this.m_CallBack[b]&&(this.m_CallBack[b]=void 0,this.count--)};a.Base.CallBacks.prototype.execute=function(){if(this.enableEvent){var b=!0,a;for(a in this.m_CallBack)switch(a){case "length":break;default:this.m_CallBack[a].enableEvent?!1===this.m_CallBack[a].fun.apply(this.obj,arguments)&&(b=!1):this.m_CallBack[a].enableEvent=this.m_CallBack[a].autoEvent}return b}this.enableEvent=this.autoEvent;return!1};a.Base.CallBacks.prototype.init_=function(a){a&&
(this.obj=a)};a.load(["LZR.Base.CallBacks"],"LZR.Base.CallBacks.CallBack");a.Base.CallBacks.CallBack=function(a){this.name="";this.autoEvent=this.enableEvent=!0;this.fun=null;a&&a.super_?a.super_.prototype.init_.call(this):this.init_(a)};a.Base.CallBacks.CallBack.prototype.className_="LZR.Base.CallBacks.CallBack";a.Base.CallBacks.CallBack.prototype.version_="1.0";a.load(null,"LZR.Base.CallBacks.CallBack");a.Base.CallBacks.CallBack.prototype.init_=function(b){b&&a.setObj(this,b)};a.load(["LZR.Base.ValCtrl",
"LZR.Base.CallBacks"],"LZR.Base.ValCtrl.Event");a.Base.ValCtrl.Event=function(b){this.before=new a.Base.CallBacks(b.self);this.change=new a.Base.CallBacks(b.self);this.set=new a.Base.CallBacks(b.self);b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.Base.ValCtrl.Event.prototype.className_="LZR.Base.ValCtrl.Event";a.Base.ValCtrl.Event.prototype.version_="1.0";a.load(null,"LZR.Base.ValCtrl.Event");a.Base.ValCtrl.Event.prototype.init_=function(b){b&&a.setObj(this,b)};a.load(["LZR.HTML5.Project.Bp.StationInfo"],
"LZR.HTML5.Project.Bp.StationInfo.SpatialLevel");a.HTML5.Project.Bp.StationInfo.SpatialLevel=function(a){this.level=0;a&&a.super_?a.super_.prototype.init_.call(this):this.init_(a)};a.HTML5.Project.Bp.StationInfo.SpatialLevel.prototype.className_="LZR.HTML5.Project.Bp.StationInfo.SpatialLevel";a.HTML5.Project.Bp.StationInfo.SpatialLevel.prototype.version_="1.0";a.load(null,"LZR.HTML5.Project.Bp.StationInfo.SpatialLevel");a.HTML5.Project.Bp.StationInfo.SpatialLevel.prototype.init_=function(b){b&&a.setObj(this,
b)};a.load(["LZR.HTML5.Project.Bp.StationInfo","LZR.HTML5.Project.Bp.StationInfo.SpatialLevel"],"LZR.HTML5.Project.Bp.StationInfo.SpatialLevelEnum");a.HTML5.Project.Bp.StationInfo.SpatialLevelEnum=function(b){this.continent=new a.HTML5.Project.Bp.StationInfo.SpatialLevel({level:500});this.country=new a.HTML5.Project.Bp.StationInfo.SpatialLevel({level:400});this.province=new a.HTML5.Project.Bp.StationInfo.SpatialLevel({level:300});this.city=new a.HTML5.Project.Bp.StationInfo.SpatialLevel({level:200});
this.point=new a.HTML5.Project.Bp.StationInfo.SpatialLevel({level:10});b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.HTML5.Project.Bp.StationInfo.SpatialLevelEnum.prototype.className_="LZR.HTML5.Project.Bp.StationInfo.SpatialLevelEnum";a.HTML5.Project.Bp.StationInfo.SpatialLevelEnum.prototype.version_="1.0";a.load(null,"LZR.HTML5.Project.Bp.StationInfo.SpatialLevelEnum");a.HTML5.Project.Bp.StationInfo.SpatialLevelEnum.prototype.init_=function(b){b&&a.setObj(this,b)};a.load(["LZR.Base",
"LZR.Base.ValCtrl"],"LZR.Base.Data");a.Base.Data=function(b){this.id=new a.Base.ValCtrl("");this.root=new a.Base.ValCtrl(null);this.parent=new a.Base.ValCtrl(null);this.children={};this.ctrl=this.view=null;this.childrenCount=0;b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.Base.Data.prototype.className_="LZR.Base.Data";a.Base.Data.prototype.version_="1.0";a.load(null,"LZR.Base.Data");a.Base.Data.prototype.append=function(a,c){c||(c=a.id.val)||(c=this.childrenCount.toString());if(a.parent.val)a.parent.val["delete"](a.id.val);
void 0===this.children[c]&&this.childrenCount++;this.children[c]=a;a.id.set(c,!1);a.parent.set(this,!1);a.root=this.root};a.Base.Data.prototype["delete"]=function(b){var c=this.children[b];void 0!==c&&(this.children[b]=void 0,c.parent.set(null,!1),c.root=new a.Base.ValCtrl(null),this.childrenCount--);return c};a.Base.Data.prototype.init_=function(b){this.root.setEventObj(this);this.id.setEventObj(this);this.id.event.change.append(this.changeId);this.parent.setEventObj(this);this.parent.event.change.append(this.changeParent);
b&&a.setObj(this,b)};a.Base.Data.prototype.changeParent=function(a){a&&a.append(this)};a.Base.Data.prototype.changeId=function(a,c,d){this.parent.val&&(this.parent.val.children[d]=void 0,this.parent.val.children[a]=this)};a.Base.Data.prototype.getById=function(a){if(a==this.id.val)return this;if(this.children[a])return this.children[a];for(var c in this.children){var d=this.children[c].getById(a);if(d)return d}return null};a.load("LZR.HTML5.Project.Bp.StationInfo LZR.Base.ValCtrl LZR.HTML5.Project.Bp.StationInfo.SpatialLevelEnum LZR.Base.Data LZR.HTML5.Project.Bp.StationInfo.Model.SpatialData LZR.HTML5.Project.Bp.StationInfo.Model.Time".split(" "),
"LZR.HTML5.Project.Bp.StationInfo.Model");a.HTML5.Project.Bp.StationInfo.Model=function(b){a.initSuper(this);this.mod=new a.Base.ValCtrl;this.map=null;this.m_data={};this.m_time=new a.HTML5.Project.Bp.StationInfo.Model.Time;b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.HTML5.Project.Bp.StationInfo.Model.prototype=a.clone(a.Base.Data.prototype,a.HTML5.Project.Bp.StationInfo.Model.prototype);a.HTML5.Project.Bp.StationInfo.Model.prototype.super_=[a.Base.Data];a.HTML5.Project.Bp.StationInfo.Model.prototype.className_=
"LZR.HTML5.Project.Bp.StationInfo.Model";a.HTML5.Project.Bp.StationInfo.Model.prototype.version_="1.0";a.load(null,"LZR.HTML5.Project.Bp.StationInfo.Model");a.HTML5.Project.Bp.StationInfo.Model.prototype.LEVEL=new a.HTML5.Project.Bp.StationInfo.SpatialLevelEnum;a.HTML5.Project.Bp.StationInfo.Model.prototype.init_=function(b){this.root.set(this);this.m_time.root.set(this);b&&a.setObj(this,b)};a.HTML5.Project.Bp.StationInfo.Model.prototype.flush=function(){};a.load(["LZR.HTML5.Project.Bp.StationInfo.Model"],
"LZR.HTML5.Project.Bp.StationInfo.Model.FomInfo");a.HTML5.Project.Bp.StationInfo.Model.FomInfo=function(a){this.time=new Date(null);this.aqi=0;this.mainFom="";this.concentration=0;a&&a.super_?a.super_.prototype.init_.call(this):this.init_(a)};a.HTML5.Project.Bp.StationInfo.Model.FomInfo.prototype.className_="LZR.HTML5.Project.Bp.StationInfo.Model.FomInfo";a.HTML5.Project.Bp.StationInfo.Model.FomInfo.prototype.version_="1.0";a.load(null,"LZR.HTML5.Project.Bp.StationInfo.Model.FomInfo");a.HTML5.Project.Bp.StationInfo.Model.FomInfo.prototype.init_=
function(b){b&&a.setObj(this,b)};a.load(["LZR.HTML5.Project.Bp.StationInfo.Model","LZR.Base.Data","LZR.Base.ValCtrl","LZR.HTML5.Project.Bp.StationInfo.Model.FomInfo"],"LZR.HTML5.Project.Bp.StationInfo.Model.SpatialData");a.HTML5.Project.Bp.StationInfo.Model.SpatialData=function(b){a.initSuper(this);this.level=this.geoJson=null;this.pro={};this.name="";this.m_fom=[];b&&b.super_?b.super_.prototype.init_.call(this):this.init_(b)};a.HTML5.Project.Bp.StationInfo.Model.SpatialData.prototype=a.clone(a.Base.Data.prototype,
a.HTML5.Project.Bp.StationInfo.Model.SpatialData.prototype);a.HTML5.Project.Bp.StationInfo.Model.SpatialData.prototype.super_=[a.Base.Data];a.HTML5.Project.Bp.StationInfo.Model.SpatialData.prototype.className_="LZR.HTML5.Project.Bp.StationInfo.Model.SpatialData";a.HTML5.Project.Bp.StationInfo.Model.SpatialData.prototype.version_="1.0";a.load(null,"LZR.HTML5.Project.Bp.StationInfo.Model.SpatialData");a.HTML5.Project.Bp.StationInfo.Model.SpatialData.prototype.init_=function(b){b&&a.setObj(this,b)};
a.HTML5.Project.Bp.StationInfo.Model.SpatialData.prototype.flushView=function(){};a.load(["LZR.HTML5.Project.Bp.StationInfo.Model","LZR.Base.ValCtrl","LZR.Base.Data"],"LZR.HTML5.Project.Bp.StationInfo.Model.Time");a.HTML5.Project.Bp.StationInfo.Model.Time=function(b){a.initSuper(this);this.productTime=new a.Base.ValCtrl;this.timeStart=new a.Base.ValCtrl;this.timeStep=new a.Base.ValCtrl;this.timeCount=new a.Base.ValCtrl;this.timeCurrentIndex=new a.Base.ValCtrl;this.ctrl=null;b&&b.super_?b.super_.prototype.init_.call(this):
this.init_(b)};a.HTML5.Project.Bp.StationInfo.Model.Time.prototype=a.clone(a.Base.Data.prototype,a.HTML5.Project.Bp.StationInfo.Model.Time.prototype);a.HTML5.Project.Bp.StationInfo.Model.Time.prototype.super_=[a.Base.Data];a.HTML5.Project.Bp.StationInfo.Model.Time.prototype.className_="LZR.HTML5.Project.Bp.StationInfo.Model.Time";a.HTML5.Project.Bp.StationInfo.Model.Time.prototype.version_="1.0";a.load(null,"LZR.HTML5.Project.Bp.StationInfo.Model.Time");a.HTML5.Project.Bp.StationInfo.Model.Time.prototype.init_=
function(b){b&&a.setObj(this,b)};return a};
